### ISSUE TITLE
Trained Model

### ISSUE THREAD

**Issue by Farihaa** [feevos/ceecnet#1]
Can I get a trained model for this work? I need to perform some inferences to understand if I can use this for my own work.

**Comment by feevos** [comment]
Hi Farihaa, thank you for your interest in our work. Unfortunately, we do not provide pre-trained models as the trained product has a commercial value for CSIRO that funded this research. It should be straightforward to set up your own runs and train the models provided in this repo. 

Kind regards,
Foivos
