### ISSUE TITLE
about environment

### ISSUE THREAD

**Issue by bluemoonwencong** [feevos/ceecnet#10]
I use these environment:

1) docker pull bitnami/mxnet:1.8.0-debian-10-r188
2) docker pull bitnami/mxnet:1.6.0
3) pip install mxnet
4) pip install mxnet-cu100
...

to run these code:
```python
import sys
sys.path.append('/mount/home/bluemoon/nas_194/repos-read/')
from mxnet import nd 
from ceecnet.models.changedetection.mantis.mantis_dn import *

# D6nf32 example 
depth=6
norm_type='GroupNorm'
norm_groups=4
ftdepth=5
NClasses=2
nfilters_init=32
psp_depth=4
nheads_start=4

net = mantis_dn_cmtsk(nfilters_init=nfilters_init, NClasses=NClasses,depth=depth, ftdepth=ftdepth, model='CEECNetV1',psp_depth=psp_depth,norm_type=norm_type,norm_groups=norm_groups,nheads_start=nheads_start)
net.initialize()

BatchSize = 4
img_size=256
NChannels = 3

input_img_1 = nd.random.uniform(shape=[BatchSize, NChannels, img_size, img_size])
input_img_2 = nd.random.uniform(shape=[BatchSize, NChannels, img_size, img_size])

outs = net(input_img_1, input_img_2)

```

, but all these environment will report error at this step “outs = net(input_img_1, input_img_2)”， the report error info is "Illegal instruction (core dumped)"

**Comment by feevos** [comment]
Hi @bluove , I assume you tried with each one of the above 4 environments and your code failed (if you tried them all, simultaneously, only the last survives). It seems this is a mxnet versioning issue. Can you please post the full error? I **may** be able to help.  I have had similar errors in the past and tried few versions of mxnet and this resolved it.

**Comment by bluemoonwencong** [comment]
@feevos   all info is bleow:
```bash
root@ad9c7b1019e9:/mount/home/bluemoon/nas_194/repos-read/ceecnet# python debug.py
depth:= 0, nfilters: 32, nheads::4, widths::1
depth:= 1, nfilters: 64, nheads::8, widths::1
depth:= 2, nfilters: 128, nheads::16, widths::1
depth:= 3, nfilters: 256, nheads::32, widths::1
depth:= 4, nfilters: 512, nheads::64, widths::1
depth:= 5, nfilters: 1024, nheads::128, widths::1
depth:= 6, nfilters: 512, nheads::128, widths::1
depth:= 7, nfilters: 256, nheads::64, widths::1
depth:= 8, nfilters: 128, nheads::32, widths::1
depth:= 9, nfilters: 64, nheads::16, widths::1
depth:= 10, nfilters: 32, nheads::8, widths::1
Illegal instruction (core dumped)
root@ad9c7b1019e9:/mount/home/bluemoon/nas_194/repos-read/ceecnet#
```
I have try "pip install mxnet-cu100", but it fail.  Could a Dockerfile will be provide ?

**Comment by feevos** [comment]
Hi @bluove , can you please try installing mxnet with command: 

```pip install mxnet-cu100==1.7.0 -f https://dist.mxnet.io/python``` 

Unfortunately I do not have time to produce a container for the environment, I apologize. It seems your problem relates to the version of mxnet and the environment, from a bit of searching on the net (e.g. https://stackoverflow.com/questions/54348348/illegal-instruction-core-dumped-while-importing-mxnet ) 

Try various versions from here https://dist.mxnet.io/python but use 1.6.0 <= version <= 1.8.0. I think when I created this model I used mxnet 1.6.0 but that is from memory, I am not sure, I apologize for the inconvenience. Also, try with / without cuda ```ctx = mx.cpu() #for cpu``` and ```ctx=mx.gpu()``` for gpu. 

Please let me know how you go with it.

**Comment by bluemoonwencong** [comment]
@feevos     after install like this "pip install mxnet-cu100==1.7.0 -f https://dist.mxnet.io/python", everything is ok. thanks!

And I have another confusing, if I only have change segmentation label and do not have boundary label and distance label.

Could I just change the 28~32 lines of ./nn/loss/mtsk_loss.py from
```python
        loss_segm  = self.ftnmt(pred_segm,   label_segm)
        loss_bound = self.ftnmt(pred_bound, label_bound)
        loss_dists = self.ftnmt(pred_dists, label_dists)

        return (loss_segm+loss_bound+loss_dists)/3.0
```
to
```
        loss_segm  = self.ftnmt(pred_segm,   label_segm)
        # loss_bound = self.ftnmt(pred_bound, label_bound)
        # loss_dists = self.ftnmt(pred_dists, label_dists)

        return loss_segm
```

thank a lot !

**Comment by feevos** [comment]
@bluove  yes, it should work, I cannot think of a reason why not. 

happy you got it fixed :). 

Cheers,
Foivos
