### ISSUE TITLE
Object Boundary in image

### ISSUE THREAD

**Issue by zhijiejia** [feevos/ceecnet#4]
hi feevos, the segmentation head in this paper, the distance is between feature1 and feature2 ? and it likes to Euclidean distance ？ and the Boundary is how to produce?  I haven't used mxnet ,  so It's difficult to read your code for me. But want to learn your ideas in segmentation head.   Can you explain your ideas briefly ? thanks

**Comment by feevos** [comment]
Hi @zhijiejia , the distance is the distance transform as defined in OpenCV (e.g. https://www.tutorialspoint.com/opencv/opencv_distance_transformation.htm), you can find many more details about this transform as well as the conditioned multitasking head in our [ResUNet-a paper - section 3.1.2](https://github.com/feevos/resuneta), that introduced the idea. We provide much more details there, and this is why we avoided repeating this meterial in our present manuscript. 

You can find source code for the boundary estimation and distance transform in  [file chopchop2rec.py](https://github.com/feevos/ceecnet/blob/897cd5c128ffd85369732d1cac82a6ddc7643afa/chopchop/chopchop2rec.py#L9) that is not mxnet source code. 

mxnet has almost identical syntax with pytorch, so it should be straightforward for you to understand it with minimal effort (assuming you are familiar with pytorch). There is also a [translation page](https://mxnet.apache.org/versions/1.7.0/api/python/docs/tutorials/getting-started/to-mxnet/pytorch.html) (for mxnet < 2.0 that this repository is based).

**Comment by zhijiejia** [comment]
ok thank you very very much, I am a beginner, thank you for your detailed reply.
